name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  NODE_FLAGS: --max_old_space_size=4096

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up project
        uses: ./.github/actions/setup-project
      - name: Build
        run: |
          rm -rf dist
          node build-scripts build
      - name: Checks
        run: node build-scripts pre-deploy
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: bemuse-build-${{ github.sha }}
          path: dist
  e2e:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up project
        uses: ./.github/actions/setup-project
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: bemuse-build-${{ github.sha }}
          path: dist
      - name: Install browsers
        run: |
          cd e2e
          npx playwright install --with-deps
      - name: Run E2E tests
        run: |
          cd e2e
          npx playwright test
      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: e2e/playwright-report
