name: Tidy

on:
  push: {}

jobs:
  tidy:
    name: Ensure codebase is tidy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up project
        uses: ./.github/actions/setup-project
      - name: Lint and fix all auto-fixable problems
        run: node common/scripts/install-run-rush.js lint-fix || true
      - name: Make sure all source files are formatted using Prettier
        run: node common/scripts/install-run-rush.js format-all || true
      - run: git add --update
      - uses: dtinth/patch-generator-action@main
