name: Tidy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  tidy:
    name: Ensure codebase is tidy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up project
        uses: ./.github/actions/setup-project
      - name: Lint and fix all auto-fixable problems
        run: node common/scripts/install-run-rush.js lint-fix
        if: always()
      - name: Make sure all source files are formatted using Prettier
        run: node common/scripts/install-run-rush.js format-all
        if: always()
      - run: git add --update
        if: always()
      - uses: dtinth/patch-generator-action@main
        if: always()
